# specify the version of docker-compose
version: "3.8"

# define the services/containers to be run
services:
  # define the frontend service
  web:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:8000
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  # define the api service/container
  api: 
    build: ./backend
    ports: 
      - 8080:8080

    # specify environment variables for the api service
    environment:
      MONGODB_URL: mongodb+srv://vansykien03:6gL9X3kgOKAqU0om@cluster0.grhch.mongodb.net/EldenRing?retryWrites=true&w=majority&appName=Cluster0   # Passes the MONGODB_URL from the .env file
      SECRET: a3sRNUt8TzPmgbXf7nDKMw
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

# define the volumes to be used by the services
volumes:
  eldenring:
